platformName: Android
app: /app/znbwl.apk
platformVersion: 5.1.1
deviceName: 127.0.0.1:62001
appPackage: com.pdswp.su.smartcalendar
appActivity: com.pdswp.su.smartcalendar.WelcomeNote
sessionOverride: True
noReset: True